docker使えるようにした
kaito071831/BingoGame pull request #4
Opened 2022-11-23 15:24 UTC by KaguraGateway

Resolve #1 

# タスク
- [x] Dockerfile書く
- [x] docker-compose.yml書く

# レビューして欲しいところ
- Dockerfile、docker-composeの書式が正しいか
- docker compose upで問題なくNext.jsが立ち上がるか

2022-11-24 09:43 UTC, kaito071831 requested changes

2022-11-24 13:07 UTC, KaguraGateway commented on docker-compose.yml
> +    image: redis:latest
短期かつ次利用するとしても来年なのであえてバージョン指定しなかったんですが、やっぱり指定した方がいいですよね。
最新バージョンのRedis7を指定しようと思うんですが、バージョンの希望ありますか？

2022-11-25 01:08 UTC, kaito071831 commented on docker-compose.yml
> +    image: redis:latest
いつ使うかによってpullしてくるredisのバージョン変わるからそれで発生する不具合が怖いので一応指定した方がいいかなと。
バージョンは最新の7で大丈夫！

2022-11-25 02:05 UTC, KaguraGateway commented on docker-compose.yml
> +    image: redis:latest
了解です！

2022-11-25 02:20 UTC, kaito071831 approved these changes
LGTM!

2022-11-25 02:21 UTC, merged